// Every Depllo feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 54 feature routes of the Depllo API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** Create an API key. (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** Revoke an API key: requests with it get 401 from now on. (DELETE /api/v1/api-keys/{id}) */
  apiKeysDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/api-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List the workspace's active API keys (newest first). (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** List audit (GET /api/v1/audit) */
  auditList(input?: { "action"?: unknown; "actor"?: unknown; "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["action"] = all["action"]; delete all["action"];
    query["actor"] = all["actor"]; delete all["actor"];
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/audit`, query, undefined);
  }

  /** POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl. (POST /api/v1/billing/checkout) */
  billingCheckout(input: { "tier": "free" | "starter" | "growth" | "business"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** Current subscription (free default) + the tier table. (GET /api/v1/billing) */
  billingList(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing`, {}, undefined);
  }

  /** Create a lint (POST /api/v1/ci/lint) */
  ciLint(input: { "configText": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/ci/lint`, query, all);
  }

  /** List download (GET /api/v1/jobs/{id}/artifacts/{artId}/download) */
  jobsArtifactsDownload(id: string, artId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/jobs/${encodeURIComponent(id)}/artifacts/${encodeURIComponent(artId)}/download`, {}, undefined);
  }

  /** Cancel a job (POST /api/v1/jobs/{id}/cancel) */
  jobsCancel(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/jobs/${encodeURIComponent(id)}/cancel`, {}, undefined);
  }

  /** Get a job (GET /api/v1/jobs/{id}) */
  jobsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/jobs/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List log (GET /api/v1/jobs/{id}/log) */
  jobsLog(id: string, input?: { "from"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["from"] = all["from"]; delete all["from"];
    return this.call("GET", `/api/v1/jobs/${encodeURIComponent(id)}/log`, query, undefined);
  }

  /** SSE tail: replays chunks from ?from= then polls the DB every ~1s. (GET /api/v1/jobs/{id}/log/stream) */
  jobsLogStream(id: string, input?: { "from"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["from"] = all["from"]; delete all["from"];
    return this.call("GET", `/api/v1/jobs/${encodeURIComponent(id)}/log/stream`, query, undefined);
  }

  /** Play a job (POST /api/v1/jobs/{id}/play) */
  jobsPlay(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/jobs/${encodeURIComponent(id)}/play`, {}, undefined);
  }

  /** Retry a job (POST /api/v1/jobs/{id}/retry) */
  jobsRetry(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/jobs/${encodeURIComponent(id)}/retry`, {}, undefined);
  }

  /** Cancel a pipeline (POST /api/v1/pipelines/{id}/cancel) */
  pipelinesCancel(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/pipelines/${encodeURIComponent(id)}/cancel`, {}, undefined);
  }

  /** Get a pipeline (GET /api/v1/pipelines/{id}) */
  pipelinesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/pipelines/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Retry a pipeline (POST /api/v1/pipelines/{id}/retry) */
  pipelinesRetry(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/pipelines/${encodeURIComponent(id)}/retry`, {}, undefined);
  }

  /** List config (GET /api/v1/projects/{id}/config) */
  projectsConfig(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/config`, {}, undefined);
  }

  /** Create a project (POST /api/v1/projects) */
  projectsCreate(input: { "name"?: string; "repoFullName": string; "defaultBranch"?: string; "configPath"?: string; "cloneToken"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects`, query, all);
  }

  /** Pipelines a project (POST /api/v1/projects/{id}/pipelines) */
  projectsCreatePipelines(id: string, input: { "ref": string; "variables"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/pipelines`, query, all);
  }

  /** Schedules a project (POST /api/v1/projects/{id}/schedules) */
  projectsCreateSchedules(id: string, input: { "cron": string; "ref": string; "active"?: boolean; "variables"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/schedules`, query, all);
  }

  /** Variables a project (POST /api/v1/projects/{id}/variables) */
  projectsCreateVariables(id: string, input: { "key": string; "value": string; "backend"?: "local" | "secronna"; "masked"?: boolean; "protected"?: boolean; "fileType"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/variables`, query, all);
  }

  /** Delete a project (DELETE /api/v1/projects/{id}) */
  projectsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/projects/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a schedule (DELETE /api/v1/projects/{id}/schedules/{schedId}) */
  projectsDeleteSchedules(id: string, schedId: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/projects/${encodeURIComponent(id)}/schedules/${encodeURIComponent(schedId)}`, {}, undefined);
  }

  /** Delete a variable (DELETE /api/v1/projects/{id}/variables/{varId}) */
  projectsDeleteVariables(id: string, varId: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/projects/${encodeURIComponent(id)}/variables/${encodeURIComponent(varId)}`, {}, undefined);
  }

  /** Get a project (GET /api/v1/projects/{id}) */
  projectsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a pipeline (GET /api/v1/projects/{id}/pipelines/{iid}) */
  projectsGetPipelines(id: string, iid: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/pipelines/${encodeURIComponent(iid)}`, {}, undefined);
  }

  /** List projects (GET /api/v1/projects) */
  projectsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/projects`, {}, undefined);
  }

  /** List pipelines (GET /api/v1/projects/{id}/pipelines) */
  projectsPipelines(id: string, input?: { "q"?: unknown; "ref"?: unknown; "source"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    query["ref"] = all["ref"]; delete all["ref"];
    query["source"] = all["source"]; delete all["source"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/pipelines`, query, undefined);
  }

  /** Cancel a pipeline (POST /api/v1/projects/{id}/pipelines/{iid}/cancel) */
  projectsPipelinesCancel(id: string, iid: string): Promise<unknown> {
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/pipelines/${encodeURIComponent(iid)}/cancel`, {}, undefined);
  }

  /** Retry a pipeline (POST /api/v1/projects/{id}/pipelines/{iid}/retry) */
  projectsPipelinesRetry(id: string, iid: string): Promise<unknown> {
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/pipelines/${encodeURIComponent(iid)}/retry`, {}, undefined);
  }

  /** List schedules (GET /api/v1/projects/{id}/schedules) */
  projectsSchedules(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/schedules`, {}, undefined);
  }

  /** Config a project (PUT /api/v1/projects/{id}/config) */
  projectsSetConfig(id: string, input: { "configText": string; "commitMessage"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/projects/${encodeURIComponent(id)}/config`, query, all);
  }

  /** Update a schedule (PATCH /api/v1/projects/{id}/schedules/{schedId}) */
  projectsUpdateSchedules(id: string, schedId: string, input?: { "cron"?: string; "ref"?: string; "active"?: boolean; "variables"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/projects/${encodeURIComponent(id)}/schedules/${encodeURIComponent(schedId)}`, query, all);
  }

  /** Update a variable (PATCH /api/v1/projects/{id}/variables/{varId}) */
  projectsUpdateVariables(id: string, varId: string, input?: { "value"?: string; "backend"?: "local" | "secronna"; "masked"?: boolean; "protected"?: boolean; "fileType"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/projects/${encodeURIComponent(id)}/variables/${encodeURIComponent(varId)}`, query, all);
  }

  /** List variables (GET /api/v1/projects/{id}/variables) */
  projectsVariables(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/variables`, {}, undefined);
  }

  /** Idempotent webhook (re)create — the settings page "re-create" button. (POST /api/v1/projects/{id}/webhook) */
  projectsWebhook(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/webhook`, {}, undefined);
  }

  /** List pipeline.svg (GET /api/v1/public/badges/{badgeToken}/pipeline.svg) */
  publicBadgesPipelineSvg(badgeToken: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/badges/${encodeURIComponent(badgeToken)}/pipeline.svg`, {}, undefined);
  }

  /** List runners (GET /api/v1/runners) */
  runnersList(): Promise<unknown> {
    return this.call("GET", `/api/v1/runners`, {}, undefined);
  }

  /** Pause a runner (POST /api/v1/runners/{id}/pause) */
  runnersPause(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/runners/${encodeURIComponent(id)}/pause`, {}, undefined);
  }

  /** Resume a runner (POST /api/v1/runners/{id}/resume) */
  runnersResume(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/runners/${encodeURIComponent(id)}/resume`, {}, undefined);
  }

  /** Delete a schedule (DELETE /api/v1/schedules/{id}) */
  schedulesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/schedules/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List schedules (GET /api/v1/schedules) */
  schedulesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/schedules`, {}, undefined);
  }

  /** Update a schedule (PATCH /api/v1/schedules/{id}) */
  schedulesUpdate(id: string, input?: { "cron"?: string; "ref"?: string; "active"?: boolean; "variables"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/schedules/${encodeURIComponent(id)}`, query, all);
  }

  /** List usage (GET /api/v1/usage) */
  usageList(): Promise<unknown> {
    return this.call("GET", `/api/v1/usage`, {}, undefined);
  }

  /** Get a webhook delivery, with every attempt made at it. (GET /api/v1/webhook-deliveries/{id}) */
  webhookDeliveriesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-deliveries/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List webhook deliveries, newest first: status (pending, succeeded, failed), attempt count, next retry, the body sent and every attempt made (`attemptLog`). (GET /api/v1/webhook-deliveries) */
  webhookDeliveriesList(input?: { "limit"?: number; "cursor"?: string; "endpointId"?: string; "status"?: "pending" | "succeeded" | "failed"; "type"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["endpointId"] = all["endpointId"]; delete all["endpointId"];
    query["status"] = all["status"]; delete all["status"];
    query["type"] = all["type"]; delete all["type"];
    return this.call("GET", `/api/v1/webhook-deliveries`, query, undefined);
  }

  /** Retry a webhook delivery: one more attempt now at a failed delivery (or send a succeeded one again). (POST /api/v1/webhook-deliveries/{id}/retry) */
  webhookDeliveriesRetry(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/webhook-deliveries/${encodeURIComponent(id)}/retry`, {}, undefined);
  }

  /** Register a webhook endpoint. (POST /api/v1/webhook-endpoints) */
  webhookEndpointsCreate(input: { "url": string; "events"?: unknown[]; "description"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhook-endpoints`, query, all);
  }

  /** Delete a webhook endpoint and its delivery log. (DELETE /api/v1/webhook-endpoints/{id}) */
  webhookEndpointsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhook-endpoints/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** The event types an endpoint can subscribe to, with what each reports. (GET /api/v1/webhook-endpoints/event-types) */
  webhookEndpointsEventTypes(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-endpoints/event-types`, {}, undefined);
  }

  /** Get a webhook endpoint. (GET /api/v1/webhook-endpoints/{id}) */
  webhookEndpointsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-endpoints/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List the workspace's webhook endpoints, newest first. (GET /api/v1/webhook-endpoints) */
  webhookEndpointsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-endpoints`, {}, undefined);
  }

  /** Update a webhook endpoint. `active: false` pauses it (its queued deliveries become failed); `active: true` re-enables it — also after Depllo switched it off for failing — and clears its failure streak (PATCH /api/v1/webhook-endpoints/{id}) */
  webhookEndpointsUpdate(id: string, input?: { "url"?: string; "events"?: unknown[]; "description"?: string; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhook-endpoints/${encodeURIComponent(id)}`, query, all);
  }

  /** @deprecated The old name of `projectsGetPipelines` (GET /api/v1/projects/{id}/pipelines/{iid}). */
  projectsPipelines2(...args: Parameters<GeneratedApi["projectsGetPipelines"]>): Promise<unknown> {
    return this.projectsGetPipelines(...args);
  }
}
